### ISSUE TITLE
Repository doesn't contain any charts

### ISSUE THREAD

**Issue by eshepelyuk** [Kuadrant/helm-charts#14]
I am following README. but receiving this error

```
helm repo add kuadrant https://kuadrant.io/helm-charts/ --force-update
helm install limitador-operator kuadrant/limitador-operator

Error: INSTALLATION FAILED: chart "limitador-operator" matching  not found in kuadrant index. (try 'helm repo update'): no chart version found for limitador-operator-
```

`helm search` also doesn't return any results

```
helm search repo authorino
No results found
```

**Comment by didierofrivia** [comment]
Hey there @eshepelyuk, hope the answer on https://github.com/Kuadrant/authorino-operator/issues/202 fixes the installation of the charts. Will close this issue, feel free to re-open or open a new one if there's something not conclusive. Cheers!
